package org.saturn.app.service.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.saturn.app.model.MessageAuditEvent;

class LogRepositoryImplTest {
  @Test
  void persistsExplicitPublicAndWhisperVisibility() throws Exception {
    try (var connection = DriverManager.getConnection("jdbc:h2:mem:audit;DB_CLOSE_DELAY=-1");
        Statement statement = connection.createStatement()) {
      statement.executeUpdate(
          """
          CREATE TABLE messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip VARCHAR, name VARCHAR NOT NULL, hash VARCHAR,
            message VARCHAR, created_on BIGINT NOT NULL, channel VARCHAR,
            visibility VARCHAR CHECK(visibility IN ('PUBLIC', 'WHISPER')))
          """);
      statement.executeUpdate(
          """
          CREATE TABLE executed_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip VARCHAR, command_name VARCHAR, arguments VARCHAR, status VARCHAR,
            created_on BIGINT NOT NULL, channel VARCHAR)
          """);
      LogRepositoryImpl repository = new LogRepositoryImpl(connection);

      repository.logMessage(
          MessageAuditEvent.publicMessage(
              "trip-a", "alice", "hash-a", "hello room", "programming", 1));
      repository.logMessage(
          MessageAuditEvent.whisper("trip-a", "alice", "hash-a", "private text", "programming", 2));

      List<String> rows = new ArrayList<>();
      try (var resultSet =
          statement.executeQuery("SELECT message, visibility FROM messages ORDER BY id")) {
        while (resultSet.next()) {
          rows.add(resultSet.getString("message") + ":" + resultSet.getString("visibility"));
        }
      }
      assertEquals(List.of("hello room:PUBLIC", "private text:WHISPER"), rows);

      repository.logCommand("trip-a", "ping", "", "SUCCESS", "programming", 3);
      try (var resultSet = statement.executeQuery("SELECT command_name FROM executed_commands")) {
        resultSet.next();
        assertEquals("ping", resultSet.getString(1));
      }
    }
  }
}
