package org.saturn.app.service.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.concurrent.LinkedBlockingQueue;
import org.junit.jupiter.api.Test;
import org.saturn.app.model.dto.User;

class UserServiceImplTest {
  @Test
  void formatsRecentAliasesWithJoiningNickFiltered() throws Exception {
    try (var connection =
            DriverManager.getConnection("jdbc:h2:mem:user_service_message;DB_CLOSE_DELAY=-1");
        Statement statement = connection.createStatement()) {
      statement.execute("SET TIME ZONE 'UTC'");
      statement.executeUpdate(
          """
          CREATE TABLE messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip VARCHAR,
            name VARCHAR NOT NULL,
            hash VARCHAR,
            message VARCHAR,
            created_on BIGINT NOT NULL,
            channel VARCHAR,
            visibility VARCHAR CHECK (visibility IN ('PUBLIC', 'WHISPER'))
          )
          """);

      long now = System.currentTimeMillis();
      try (PreparedStatement insert =
          connection.prepareStatement(
              "INSERT INTO messages (trip, name, hash, message, created_on) VALUES (?, ?, ?, ?, ?)")) {
        insert.setString(1, "trip-a");
        insert.setString(2, "Alice");
        insert.setString(3, "hash-a");
        insert.setString(4, "JOINED");
        insert.setLong(5, now);
        insert.executeUpdate();

        insert.setString(2, "NEW-USER");
        insert.setString(4, "LEFT");
        insert.executeUpdate();
      }

      User user = new User("new-user");
      user.setTrip("trip-a");
      user.setHash("hash-a");

      var result =
          new UserServiceImpl(connection, new LinkedBlockingQueue<>()).isSeenRecently(user);

      assertTrue(result.isPresent());
      assertEquals("\\n @new-user, has been seen as: _Alice_ recently. \\n", result.orElseThrow());
      assertTrue(result.orElseThrow().contains("recently."));
      assertFalse(result.orElseThrow().contains("in the last 15 minutes"));
      assertFalse(result.orElseThrow().contains("NEW-USER"));
      assertFalse(result.orElseThrow().contains("new-user_"));
      assertTrue(result.orElseThrow().contains("\\n"));
      assertFalse(result.orElseThrow().contains("\n"));
    }
  }
}
