dbPath = "database/database.db"
wsUrl = "wss://hack.chat/chat-ws"
cmdPrefix = "*"
channel = "programming"
nick = "korin"
trip = "ZP7C56HozJDNDOiGMDjERMWrkf8IQVa1SH3FJdsKz0mefey9N7y9fZxmK0u63s2Nfuqg5gm3bbJqzRfKbvPDU66KurV2Jer9nmcB2SpzNtzcCHXYPLRiuU85nsx5dNQw"
userTrips = ""
adminTrips = "g0KY09"
proxies = ""
autoReconnect = true
healthCheckInterval = 5
autorunCommands = "replica lounge, say hello lads!!"
