dbPath = "database/database.db"
wsUrl = "wss://hack.chat/chat-ws"
cmdPrefix = "-"
channel = "programming"
nick = "alpha"
trip = "secret13"
userTrips = ""
adminTrips = "g0KY09"
proxies = ""
autoReconnect = false
healthCheckInterval = 15000
autorunCommands = "/whisper alphaBot *replica lounge, /whisper alphaBot *say hello lads!"
