CREATE TABLE IF NOT EXISTS banned_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip VARCHAR, name VARCHAR, hash VARCHAR, reason VARCHAR, created_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS executed_commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip VARCHAR, command_name VARCHAR, arguments VARCHAR, status VARCHAR,
  created_on BIGINT NOT NULL, channel VARCHAR
);
CREATE TABLE IF NOT EXISTS mail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner VARCHAR NOT NULL, receiver VARCHAR NOT NULL, message VARCHAR, status VARCHAR NOT NULL,
  created_on BIGINT NOT NULL, is_whisper VARCHAR
);
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip VARCHAR, name VARCHAR NOT NULL, hash VARCHAR, message VARCHAR,
  created_on BIGINT NOT NULL, channel VARCHAR,
  visibility VARCHAR CHECK (visibility IN ('PUBLIC', 'WHISPER'))
);
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip VARCHAR, note VARCHAR, created_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR NOT NULL CHECK (type IN ('ADMIN', 'MODERATOR', 'TRUSTED', 'USER', 'REGULAR', 'PEST')),
  trip VARCHAR UNIQUE, created_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS names (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR UNIQUE, created_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS trip_names (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id BIGINT NOT NULL, name_id BIGINT NOT NULL,
  FOREIGN KEY (trip_id) REFERENCES trips(id),
  FOREIGN KEY (name_id) REFERENCES names(id),
  UNIQUE (trip_id, name_id)
);
CREATE TABLE IF NOT EXISTS dbz_characters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR, level INTEGER, created_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS dbz_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  char_id BIGINT NOT NULL, str INTEGER, agi INTEGER, vit INTEGER, ene INTEGER,
  free_stats INTEGER, created_on BIGINT NOT NULL,
  FOREIGN KEY (char_id) REFERENCES dbz_characters(id)
);
CREATE TABLE IF NOT EXISTS agent_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_key VARCHAR NOT NULL, role VARCHAR NOT NULL CHECK (role IN ('user', 'assistant')),
  content VARCHAR NOT NULL, created_on BIGINT NOT NULL, expires_on BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS agent_tool_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identity_key VARCHAR NOT NULL, tool_name VARCHAR NOT NULL, content VARCHAR NOT NULL,
  created_on BIGINT NOT NULL, expires_on BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_trip_created_on ON messages (trip, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_messages_name_created_on ON messages (name, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_messages_hash_created_on ON messages (hash, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_messages_channel_created_on ON messages (channel, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_name_room_visibility_created ON messages (name, channel, visibility, created_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_name_visibility_created ON messages (name, visibility, created_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_room_visibility_created ON messages (channel, visibility, created_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_trip_visibility_created ON messages (trip, visibility, created_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_visibility ON messages (visibility);
CREATE INDEX IF NOT EXISTS idx_mail_status_receiver ON mail (status, receiver);
CREATE INDEX IF NOT EXISTS idx_notes_trip_created_on ON notes (trip, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_executed_commands_channel_created_on ON executed_commands (channel, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_banned_users_name ON banned_users (name);
CREATE INDEX IF NOT EXISTS idx_banned_users_trip ON banned_users (trip);
CREATE INDEX IF NOT EXISTS idx_banned_users_hash ON banned_users (hash);
CREATE INDEX IF NOT EXISTS idx_agent_memory_identity_created ON agent_memory (identity_key, created_on DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memory_expires ON agent_memory (expires_on);
CREATE INDEX IF NOT EXISTS idx_agent_tool_memory_identity_created ON agent_tool_memory (identity_key, created_on DESC);
