package org.saturn.app.agent.tool;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.moandjiezana.toml.Toml;
import java.sql.DriverManager;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.saturn.app.agent.AgentContext;
import org.saturn.app.agent.AgentInvocation;
import org.saturn.app.facade.EngineType;
import org.saturn.app.facade.impl.EngineImpl;
import org.saturn.app.service.AgentService;

class EngineSaturnCommandGatewayTest {
  @Test
  void returnsFalseWhenTheCommandReportsFailedStatus() throws Exception {
    try (var connection =
            DriverManager.getConnection("jdbc:h2:mem:gateway-failed;DB_CLOSE_DELAY=-1");
        var statement = connection.createStatement()) {
      statement.executeUpdate(
          """
          CREATE TABLE executed_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip TEXT,
            command_name TEXT,
            arguments TEXT,
            status TEXT,
            created_on BIGINT NOT NULL,
            channel TEXT)
          """);
      EngineImpl engine = new EngineImpl(connection, config(), EngineType.HOST);
      EngineSaturnCommandGateway gateway = new EngineSaturnCommandGateway(engine);

      boolean executed = gateway.execute(context(), "time", "");

      assertFalse(executed);
    }
  }

  @Test
  void returnsEmptyModelDataWhenTheCommandExecutionFails() throws Exception {
    try (var connection =
            DriverManager.getConnection("jdbc:h2:mem:gateway-failed-result;DB_CLOSE_DELAY=-1");
        var statement = connection.createStatement()) {
      statement.executeUpdate(
          """
          CREATE TABLE executed_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip TEXT,
            command_name TEXT,
            arguments TEXT,
            status TEXT,
            created_on BIGINT NOT NULL,
            channel TEXT)
          """);
      EngineImpl engine = new EngineImpl(connection, config(), EngineType.HOST);
      EngineSaturnCommandGateway gateway = new EngineSaturnCommandGateway(engine);

      SaturnCommandGateway.CommandExecution result =
          gateway.executeWithResult(context(), "time", "");

      assertFalse(result.executed());
      assertTrue(result.modelData().isEmpty());
    }
  }

  @Test
  void returnsFallbackModelDataWhenSuccessfulCommandProducesNoChatOutput() throws Exception {
    try (var connection =
            DriverManager.getConnection("jdbc:h2:mem:gateway-silent;DB_CLOSE_DELAY=-1");
        var statement = connection.createStatement()) {
      statement.executeUpdate(
          """
          CREATE TABLE executed_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip TEXT,
            command_name TEXT,
            arguments TEXT,
            status TEXT,
            created_on BIGINT NOT NULL,
            channel TEXT)
          """);
      EngineImpl engine = new SilentAgentEngine(connection, config());
      EngineSaturnCommandGateway gateway = new EngineSaturnCommandGateway(engine);

      SaturnCommandGateway.CommandExecution result =
          gateway.executeWithResult(context(), "l", "question");

      assertTrue(result.executed());
      assertEquals(
          "Saturn command 'l' executed; its output was sent to the room. No other Saturn command was executed.",
          result.modelData());
    }
  }

  @Test
  void returnsOnlyTheAgentTriggeredCommandOutputToTheModel() throws Exception {
    try (var connection =
            DriverManager.getConnection("jdbc:h2:mem:gateway-output;DB_CLOSE_DELAY=-1");
        var statement = connection.createStatement()) {
      statement.executeUpdate(
          """
          CREATE TABLE executed_commands (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trip TEXT,
            command_name TEXT,
            arguments TEXT,
            status TEXT,
            created_on BIGINT NOT NULL,
            channel TEXT)
          """);
      EngineImpl engine = new EngineImpl(connection, config(), EngineType.HOST);
      EngineSaturnCommandGateway gateway = new EngineSaturnCommandGateway(engine);

      SaturnCommandGateway.CommandExecution result =
          gateway.executeWithResult(context(), "version", "ignored");

      assertTrue(result.executed());
      assertTrue(result.modelData().startsWith("@alice "));
      assertFalse(result.modelData().contains("Saturn command 'version' executed"));
      assertTrue(engine.outgoingMessageQueue.contains(result.modelData()));
    }
  }

  private static final class SilentAgentEngine extends EngineImpl {
    private SilentAgentEngine(java.sql.Connection connection, Toml config) {
      super(connection, config, EngineType.HOST);
      setAgentService(
          new AgentService() {
            @Override
            public boolean submit(AgentInvocation invocation) {
              return true;
            }

            @Override
            public void close() {}
          });
    }
  }

  private AgentContext context() {
    return new AgentContext("programming", "alice", "trip-a", "hash-a", false, List.of("alice"));
  }

  private Toml config() {
    return new Toml()
        .read(
            """
            cmdPrefix = "*"
            channel = "programming"
            nick = "saturn"
            trip = "secret13"
            userTrips = ""
            adminTrips = ""
            wsUrl = "wss://hack.chat/chat-ws"
            proxies = ""
            autorunCommands = ""
            """);
  }
}
