package org.saturn.app.agent.persistence;

import java.sql.SQLException;
import java.sql.Statement;
import org.saturn.app.persistence.H2Database;

public final class AgentSchemaMigrator {
  private AgentSchemaMigrator() {}

  public static void migrate(String databasePath) {
    try (var connection = H2Database.open(databasePath)) {
      connection.setAutoCommit(false);
      try (Statement statement = connection.createStatement()) {
        statement.executeUpdate(
            """
            CREATE TABLE IF NOT EXISTS agent_memory (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              identity_key VARCHAR NOT NULL,
              role VARCHAR NOT NULL CHECK(role IN ('user', 'assistant')),
              content VARCHAR NOT NULL,
              created_on BIGINT NOT NULL,
              expires_on BIGINT NOT NULL)
            """);
        statement.executeUpdate(
            """
            CREATE INDEX IF NOT EXISTS idx_agent_memory_identity_created
            ON agent_memory (identity_key, created_on DESC)
            """);
        statement.executeUpdate(
            """
            CREATE INDEX IF NOT EXISTS idx_agent_memory_expires
            ON agent_memory (expires_on)
            """);
        statement.executeUpdate(
            """
            CREATE TABLE IF NOT EXISTS agent_tool_memory (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              identity_key VARCHAR NOT NULL,
              tool_name VARCHAR NOT NULL,
              content VARCHAR NOT NULL,
              created_on BIGINT NOT NULL,
              expires_on BIGINT NOT NULL)
            """);
        statement.executeUpdate(
            """
            CREATE INDEX IF NOT EXISTS idx_agent_tool_memory_identity_created
            ON agent_tool_memory (identity_key, created_on DESC)
            """);
      }
      connection.commit();
    } catch (SQLException exception) {
      throw new AgentPersistenceException("Agent schema migration failed", exception);
    }
  }
}
